export const GET_RECIPE_BY_RECIPE_ID_START = 'GET_RECIPE_BY_RECIPE_ID_START';
export const GET_RECIPE_BY_RECIPE_ID_SUCCESS = 'GET_RECIPE_BY_RECIPE_ID_SUCCESS';
export const GET_RECIPE_BY_RECIPE_ID_FAILED = 'GET_RECIPE_BY_RECIPE_ID_FAILED';
export const GET_ALL_USER_RECIPES_START = 'GET_ALL_USER_RECIPES_START';
export const GET_ALL_USER_RECIPES_SUCCESS = 'GET_ALL_USER_RECIPES_SUCCESS';
export const GET_ALL_USER_RECIPES_FAILED = 'GET_ALL_USER_RECIPES_FAILED';
// export const GET_OTHER_USER_RECIPES_START = 'GET_OTHER_USER_RECIPES_START';
// export const GET_OTHER_USER_RECIPES_SUCCESS = 'GET_OTHER_USER_RECIPES_SUCCESS';
// export const GET_OTHER_USER_RECIPES_FAILED = 'GET_OTHER_USER_RECIPES_FAILED';
export const GET_OTHER_USER_ID_START = 'GET_OTHER_USER_ID_START';
export const GET_OTHER_USER_ID_SUCCESS = 'GET_OTHER_USER_ID_SUCCESS';
export const GET_OTHER_USER_ID_FAILED = 'GET_OTHER_USER_ID_FAILED';

export const CLEAR_SEARCHED_USER_ID = 'CLEAR_SEARCHED_USER_ID';
export const CLEAR_IS_TABS_DESELECT = 'CLEAR_IS_TABS_DESELECT';

export const CREATE_RECIPE_INIT = 'CREATE_RECIPE_INIT';
export const CREATE_RECIPE_START = 'CREATE_RECIPE_START';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILED = 'CREATE_RECIPE_FAILED';

export const UPDATE_RECIPE_INIT = 'UPDATE_RECIPE_INIT';
export const UPDATE_RECIPE_START = 'UPDATE_RECIPE_START';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILED = 'UPDATE_RECIPE_FAILED';

export const DELETE_RECIPE_INIT = 'DELETE_RECIPE_INIT';
export const DELETE_RECIPE_START = 'DELETE_RECIPE_START';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAILED = 'DELETE_RECIPE_FAILED';

export const SET_NAME_AND_TITLE_START = 'SET_NAME_AND_TITLE_START';
export const SET_NAME_AND_TITLE_SUCCESS = 'SET_NAME_AND_TITLE_SUCCESS';
export const SET_NAME_AND_TITLE_FAILED = 'SET_NAME_AND_TITLE_FAILED';
export const SET_PROFILE_PIC_START = 'SET_PROFILE_PIC_START';
export const SET_PROFILE_PIC_SUCCESS = 'SET_PROFILE_PIC_SUCCESS';
export const SET_PROFILE_PIC_FAILED = 'SET_PROFILE_PIC_FAILED';
export const SET_ABOUT_ME_START = 'SET_ABOUT_ME_START';
export const SET_ABOUT_ME_SUCCESS = 'SET_ABOUT_ME_SUCCESS';
export const SET_ABOUT_ME_FAILED = 'SET_ABOUT_ME_FAILED';
export const SET_FAVE_COOKS_START = 'SET_FAVE_COOKS_START';
export const SET_FAVE_COOKS_SUCCESS = 'SET_FAVE_COOKS_SUCCESS';
export const SET_FAVE_COOKS_FAILED = 'SET_FAVE_COOKS_FAILED';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const AUTO_LOGIN_START = 'AUTO_LOGIN_START';
export const AUTO_LOGIN_SUCCESS = 'AUTO_LOGIN_SUCCESS';
export const AUTO_LOGIN_FAILED = 'AUTO_LOGIN_FAILED';
export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';
export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILED = 'AUTH_SIGNUP_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';