export const CREATE_RECIPE_INIT = 'CREATE_RECIPE_INIT';
export const CREATE_RECIPE_START = 'CREATE_RECIPE_START';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILED = 'CREATE_RECIPE_FAILED';

export const UPDATE_RECIPE_INIT = 'UPDATE_RECIPE_INIT';
export const UPDATE_RECIPE_START = 'UPDATE_RECIPE_START';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILED = 'UPDATE_RECIPE_FAILED';

export const SET_NAME_AND_TITLE_START = 'SET_NAME_AND_TITLE_START';
export const SET_NAME_AND_TITLE_SUCCESS = 'SET_NAME_AND_TITLE_SUCCESS';
export const SET_NAME_AND_TITLE_FAILED = 'SET_NAME_AND_TITLE_FAILED';
export const SET_ABOUT_ME_START = 'SET_ABOUT_ME_START';
export const SET_ABOUT_ME_SUCCESS = 'SET_ABOUT_ME_SUCCESS';
export const SET_ABOUT_ME_FAILED = 'SET_ABOUT_ME_FAILED';
export const SET_FAVE_COOKS_START = 'SET_FAVE_COOKS_START';
export const SET_FAVE_COOKS_SUCCESS = 'SET_FAVE_COOKS_SUCCESS';
export const SET_FAVE_COOKS_FAILED = 'SET_FAVE_COOKS_FAILED';