// export const BASIC_INFO_INPUT_CHANGED = 'BASIC_INFO_INPUT_CHANGED';
export const PREP_TIME_CHANGED = 'PREP_TIME_CHANGED';
export const PREP_TIME_UNIT_CHANGED = 'PREP_TIME_UNIT_CHANGED';
export const COOK_TIME_CHANGED = 'COOK_TIME_CHANGED';
export const COOK_TIME_UNIT_CHANGED = 'COOK_TIME_UNIT_CHANGED';
export const SERVINGS_CHANGED = 'SERVINGS_CHANGED';
export const DIFFICULTY_CHANGED = 'DIFFICULTY_CHANGED';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const ADD_DIRECTION = 'ADD_DIRECTION';
export const REMOVE_DIRECTION = 'REMOVE_DIRECTION';