export const CREATE_RECIPE_INIT = 'CREATE_RECIPE_INIT';
export const CREATE_RECIPE_START = 'CREATE_RECIPE_START';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILED = 'CREATE_RECIPE_FAILED';

export const UPDATE_RECIPE_INIT = 'UPDATE_RECIPE_INIT';
export const UPDATE_RECIPE_START = 'UPDATE_RECIPE_START';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILED = 'UPDATE_RECIPE_FAILED';